directory/config/routes.rb
Rails.application.routes.draw do
  root to: "games#index"
  resources :users, only: [:new, :create, :show, :destroy]
  resources :reviews
  resources :games

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'
end

directory/app/models/game.rb
class Game < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :name, :developer, :genre, :publisher, :platform, :rating, :imgurl, :score, :review, presence: true
end

directory/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  validates :username, :body, :game_id, presence: true
  validates :rating, numericality: true, inclusion: { in: 1..10 }
end

directory/app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  has_secure_password
end

directory/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def authenticate
    redirect_to new_user_path unless session[:current_user_id]
  end

  def current_user
    User.find(session[:current_user_id]) if session[:current_user_id]
  end

end

directory/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to games_path
    else
      redirect_to new_game_path
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
    redirect_to game_path(@game)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    if @game.save
      redirect_to games_path
    else
      redirect_to games_path(game)
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :developer, :genre, :publisher, :platform, :rating, :imgurl, :score, :review)
  end
end

directory/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
    @games = Game.all
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to games_path(@game)
    else
      redirect_to new_review_path
    end
  end

  def edit
    @review = Review.find(params[:id])
    @games = Game.all
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to review_path
  end

  private

  def review_params
    params.require(:review).permit(:username, :rating, :body, :game_id)
  end
end

directory/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to games_path
    else
      redirect_to splash_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

directory/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to games_path
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    session[:current_user_id] = nil
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

directory/app/helpers/application_helper.rb
module ApplicationHelper
end

directory/app/helpers/games_helper.rb
module GamesHelper
end

directory/app/helpers/reviews_helper.rb
module ReviewsHelper
end

directory/app/helpers/sessions_helper.rb
module SessionsHelper
end

directory/app/helpers/users_helper.rb
module UsersHelper
end

directory/app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :developer %><br>
  <%= f.text_field :developer %><br><br>
  <%= f.label  :genre %><br>
  <%= f.text_field :genre %><br><br>
  <%= f.label  :publisher %><br>
  <%= f.text_field :publisher %><br><br>
  <%= f.label  :platform %><br>
  <%= f.text_field :platform %><br><br>
  <%= f.label  :rating %><br>
  <%= f.text_field :rating %><br><br>
  <%= f.label  :imgurl %><br>
  <%= f.text_field :imgurl %><br><br>
  <%= f.label  :score %><br>
  <%= f.text_field :score %><br><br>
  <%= f.label  :review %><br>
  <%= f.text_area :review, cols: 80, rows: 10%><br><br>
  <%= f.submit %>
<% end %>

directory/app/views/games/edit.html.erb
<h1>Would you like to edit this game?</h1>

<%= render partial: 'form'%>

directory/app/views/games/index.html.erb
<%= link_to "Add a game", new_game_path %>
<div class="games-page">
  <% @games.order('name').each do |game| %>
    <h4><%= game.name %></h4>
    <img src="<%= game.imgurl %>" style="width: 200px">
    <p>
      <%= link_to "More info", game_path(game) %>
    </p>
  <% end %>
</div>

directory/app/views/games/new.html.erb
<h1>Would you like to add a new game?</h1>

<%= render partial: 'form'%>

directory/app/views/games/show.html.erb
<div class="games-page">
  <%= link_to "Return to main page", games_path %>
  <h2><%= @game.name %></h2>
  <img src="<%= @game.imgurl %>" style="width: 200px">
  <ul>
    <p><%= 'Developer: ' + @game.developer %></li>
    <p><%= 'Genre: ' + @game.genre %></li>
    <p><%= 'Publisher: ' + @game.publisher %></li>
    <p><%= 'Platform: ' + @game.platform %></li>
  </ul>
  <h3>Review</h3>
  <h4><%= @game.score %></h4>
  <p>
    <%= @game.review %>
  </p>

  <%= link_to "Edit this game?", edit_game_path %>
  <%= link_to 'DELETE THIS GAME', @game, :method => :delete %>
</div>

directory/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="login">
    <% if session[:current_user_id] %>
    <%= link_to "#{User.find(session[:current_user_id]).username}", user_path(session[:current_user_id]) %> ||
    <%= link_to "Logout", sessions_path, method: :delete %>
    <% else %>
    <p>Already A Memeber</p>
    <%= form_tag(sessions_path) do%>
    <%= label_tag :username %>:
    <%= text_field_tag :username %>
    <br>
    <%= label_tag :password %>:
    <%= password_field_tag :password %>
    <br><br>
    <%= submit_tag "Login"%>
    <% end %>
    <% end %>
  </div>
  <%= yield %>
</body>
</html>

directory/app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br><br>
  <%= f.label :rating %><br>
  <%= f.text_field :rating %><br><br>
  <%= f.label  :body %><br>
  <%= f.text_field :body, :size => 150 %><br><br>
  <%= f.submit %>
<% end %>

directory/app/views/reviews/_review.html.erb
<%= button_to "Return to main page?", games_path %>

<h1><%= review.rating %></h1>

directory/app/views/reviews/new.html.erb
<%= render partial: 'form'%>

directory/app/views/users/new.html.erb
<div class="form">
  <p>Not A Memeber Yet</p>
  <%= form_for @user do |f| %>
    <%= f.label :username%><br>
    <%= f.text_field :username%><br>
    <%= f.label :email%><br>
    <%= f.text_field :email%><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <br>
    <%= f.submit "Sign Up"%><br>
  <% end %>
</div>

directory/app/views/users/show.html.erb
<%= button_to "Return to main page", games_path %>

<div id="user-page">
  <h1>Welcome <%= @user.username %></h1>
  <%= button_to "Return to main page?", games_path %>
  <h1>Would you like to delete your account? If so click below</h1>
  <%= button_to 'DELETE THIS ACCOUNT', @user, :method => :delete %>
</div>